/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./views/AboutView.vue')['default']
    App: typeof import('./App.vue')['default']
    CommonFooter: typeof import('./components/CommonFooter/index.vue')['default']
    CommonHeader: typeof import('./components/CommonHeader/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Index: typeof import('./views/Index.vue')['default']
    Login: typeof import('./views/Login.vue')['default']
    Logo: typeof import('./views/Logo/index.vue')['default']
    NotFound: typeof import('./views/NotFound.vue')['default']
    Pack: typeof import('./views/Pack/index.vue')['default']
    Poster: typeof import('./views/Poster/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./views/Select.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
